#!/usr/bin/env node

// ============================================================================
// linda create-firm — Interactive CLI wizard for bootstrapping a firm runtime.
//
// Three blocks:
//   Block 1 — Firm Identity (id, name, packs, language, tone)
//   Block 2 — Client Agent / WhatsApp (intake channel)
//   Block 3 — Admin Agent / Telegram (operator channel)
//
// Output: a ready-to-use .env file in the current directory.
// Usage:  linda create-firm [--out .env.acme_law]
// ============================================================================

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { createInterface } from "node:readline";

// ============================================================================
// Non-interactive mode: --config=<json>
// Useful for CI, scripting, and testing without a TTY.
// Example:
//   linda-create-firm --config='{"firmId":"acme","firmName":"Acme","activePacks":["relocation_v1"],
//     "language":"ru","tone":"formal","waEnabled":true,"waAuthDir":"./.linda/auth/acme-wa",
//     "waAllowedUserIds":"","tgEnabled":true,"tgToken":"bot123","tgAllowedUserIds":"12345",
//     "psfBaseUrl":"http://localhost:3000","psfSecret":"secret","anthropicKey":"sk-ant-..."}'
// ============================================================================

interface FirmAnswers {
	firmId: string;
	firmName?: string;
	activePacks?: string;
	defaultPackId?: string;
	language?: string;
	tone?: string;
	waEnabled?: boolean;
	waAuthDir?: string;
	waAllowedUserIds?: string;
	tgEnabled?: boolean;
	tgToken?: string;
	tgAllowedUserIds?: string;
	psfBaseUrl?: string;
	psfSecret: string;
	anthropicKey?: string;
}

const configArg = process.argv.find((a) => a.startsWith("--config="))?.slice(9);
const nonInteractive = configArg !== undefined;

// ============================================================================
// Tiny readline prompt helpers
// ============================================================================

const rl = nonInteractive ? null : createInterface({ input: process.stdin, output: process.stdout });

function ask(question: string): Promise<string> {
	if (!rl) return Promise.resolve("");
	return new Promise((resolve) => rl.question(question, (ans) => resolve(ans.trim())));
}

function askDefault(question: string, def: string): Promise<string> {
	if (!rl) return Promise.resolve(def);
	return new Promise((res) => rl.question(`${question} [${def}]: `, (ans) => res(ans.trim() || def)));
}

function askBool(question: string, def: boolean): Promise<boolean> {
	if (!rl) return Promise.resolve(def);
	const hint = def ? "Y/n" : "y/N";
	return new Promise((res) =>
		rl.question(`${question} [${hint}]: `, (ans) => {
			const v = ans.trim().toLowerCase();
			if (v === "") res(def);
			else res(v === "y" || v === "yes" || v === "1" || v === "true");
		}),
	);
}

function section(title: string): void {
	console.log(`\n${"─".repeat(58)}`);
	console.log(`  ${title}`);
	console.log("─".repeat(58));
}

function note(text: string): void {
	console.log(`  ↳ ${text}`);
}

// ============================================================================
// .env generator — pure function, called by both wizard and --config= mode
// ============================================================================

interface EnvSpec {
	firmId: string;
	firmName: string;
	activePacks: string[];
	defaultPackId: string;
	language: string;
	tone: string;
	waEnabled: boolean;
	waAuthDir: string;
	waAllowedUserIds: string;
	tgEnabled: boolean;
	tgToken: string;
	tgAllowedUserIds: string;
	psfBaseUrl: string;
	psfSecret: string;
	anthropicKey: string;
}

function generateEnvFile(spec: EnvSpec): void {
	const outArg = process.argv.find((a) => a.startsWith("--out="))?.slice(6);
	const outFile = outArg ?? ".env";
	const outPath = resolve(process.cwd(), outFile);

	const lines: string[] = [
		"# ============================================================================",
		`# Linda — Firm Runtime Config: ${spec.firmName} (${spec.firmId})`,
		`# Generated by: linda-create-firm`,
		`# Date: ${new Date().toISOString().slice(0, 10)}`,
		"# ============================================================================",
		"",
		"# Block 1 — Firm Identity",
		`FIRM_ID=${spec.firmId}`,
		`FIRM_NAME=${spec.firmName}`,
		`FIRM_LANGUAGE=${spec.language}`,
		`FIRM_TONE=${spec.tone}`,
		spec.activePacks.length > 0 ? `FIRM_ACTIVE_PACKS=${spec.activePacks.join(",")}` : "# FIRM_ACTIVE_PACKS=",
		spec.defaultPackId ? `FIRM_DEFAULT_PACK_ID=${spec.defaultPackId}` : "# FIRM_DEFAULT_PACK_ID=",
		"",
		"# Block 2 — Client Agent (WhatsApp)",
		`WHATSAPP_ENABLED=${spec.waEnabled}`,
		...(spec.waEnabled
			? [
					`WHATSAPP_AUTH_DIR=${spec.waAuthDir}`,
					spec.waAllowedUserIds
						? `WHATSAPP_ALLOWED_USER_IDS=${spec.waAllowedUserIds}`
						: "# WHATSAPP_ALLOWED_USER_IDS=",
				]
			: []),
		"",
		"# Block 3 — Admin Agent (Telegram)",
		`TELEGRAM_ADMIN_ENABLED=${spec.tgEnabled}`,
		...(spec.tgEnabled
			? [
					`TELEGRAM_BOT_TOKEN=${spec.tgToken}`,
					spec.tgAllowedUserIds
						? `TELEGRAM_ALLOWED_USER_IDS=${spec.tgAllowedUserIds}`
						: "# TELEGRAM_ALLOWED_USER_IDS=   # WARN: empty = allow all",
				]
			: []),
		"",
		"# Infrastructure",
		`PSF_BASE_URL=${spec.psfBaseUrl}`,
		`PSF_SHARED_SECRET=${spec.psfSecret}`,
		"LLM_PROVIDER=anthropic",
		"LLM_MODEL=claude-sonnet-4-5",
		`ANTHROPIC_API_KEY=${spec.anthropicKey}`,
		"",
	];

	writeFileSync(outPath, lines.join("\n"), "utf-8");
	console.log(`\n✅  Written to: ${outPath}`);
	const steps: string[] = [];
	if (spec.waEnabled) steps.push("Run `linda` — WhatsApp will show a QR code on first start");
	if (spec.tgEnabled) steps.push("Telegram admin bot is ready at your @BotFather token");
	steps.push(`Make sure PSF is running at ${spec.psfBaseUrl}`);
	steps.forEach((s, i) => {
		console.log(`  ${i + 1}. ${s}`);
	});
	console.log("");
}

// ============================================================================
// Wizard
// ============================================================================

async function wizard(): Promise<void> {
	// -- Non-interactive mode: all answers from --config=<json> --
	if (nonInteractive && configArg) {
		let answers: FirmAnswers;
		try {
			answers = JSON.parse(configArg) as FirmAnswers;
		} catch {
			console.error("  ✗ --config value is not valid JSON.");
			process.exit(1);
		}
		if (!answers.firmId) {
			console.error("  ✗ firmId is required.");
			process.exit(1);
		}
		if (!answers.psfSecret) {
			console.error("  ✗ psfSecret is required.");
			process.exit(1);
		}

		const tgEnabled = answers.tgEnabled ?? true;
		if (tgEnabled && !answers.tgToken) {
			console.error("  ✗ tgToken is required when tgEnabled=true.");
			process.exit(1);
		}

		const waEnabled = answers.waEnabled ?? true;
		const activePacks = (answers.activePacks ?? "")
			.split(",")
			.map((s) => s.trim())
			.filter(Boolean);
		if (waEnabled && activePacks.length === 0 && !answers.defaultPackId) {
			console.error("  ✗ waEnabled=true but no activePacks or defaultPackId.");
			process.exit(1);
		}

		generateEnvFile({
			firmId: answers.firmId,
			firmName: answers.firmName ?? answers.firmId,
			activePacks,
			defaultPackId: answers.defaultPackId ?? "",
			language: answers.language ?? "ru",
			tone: answers.tone ?? "warm",
			waEnabled,
			waAuthDir: answers.waAuthDir ?? `./.linda/auth/${answers.firmId}-whatsapp`,
			waAllowedUserIds: answers.waAllowedUserIds ?? "",
			tgEnabled,
			tgToken: answers.tgToken ?? "",
			tgAllowedUserIds: answers.tgAllowedUserIds ?? "",
			psfBaseUrl: answers.psfBaseUrl ?? "http://localhost:3000",
			psfSecret: answers.psfSecret,
			anthropicKey: answers.anthropicKey ?? "",
		});
		return;
	}

	console.log("\n╔══════════════════════════════════════════════════════╗");
	console.log("║  Linda — Create Firm Runtime                         ║");
	console.log("║  Bootstraps a role-aware .env for one firm instance  ║");
	console.log("╚══════════════════════════════════════════════════════╝");

	// ────────────────────────────────────────────────────
	// Block 1 — Firm Identity
	// ────────────────────────────────────────────────────

	section("Block 1 / 3 — Firm Identity");

	const firmId = await ask("  FIRM_ID (e.g. acme_law_il): ");
	if (!firmId) {
		console.error("  ✗ FIRM_ID is required.");
		process.exit(1);
	}

	const firmName = await askDefault("  FIRM_NAME (display name)", firmId);

	note("Active packs: comma-separated PSF pack IDs this firm can use.");
	note("Leave empty to allow all (dev/single-firm setup).");
	const activePacksRaw = await ask("  FIRM_ACTIVE_PACKS (e.g. relocation_v1,financial_v1): ");
	const activePacks = activePacksRaw
		.split(",")
		.map((s) => s.trim())
		.filter(Boolean);

	let defaultPackId = "";
	if (activePacks.length === 1) {
		const useDefault = await askBool(
			`  Use "${activePacks[0]}" as FIRM_DEFAULT_PACK_ID (skip intent detection)?`,
			true,
		);
		if (useDefault) defaultPackId = activePacks[0];
	} else if (activePacks.length > 1) {
		note("Default pack skips intent detection. Leave empty to use intent routing.");
		defaultPackId = await ask(`  FIRM_DEFAULT_PACK_ID (one of: ${activePacks.join(", ")}), or empty: `);
		if (defaultPackId && !activePacks.includes(defaultPackId)) {
			console.error(`  ✗ "${defaultPackId}" is not in [${activePacks.join(", ")}]`);
			process.exit(1);
		}
	}

	const language = await askDefault("  FIRM_LANGUAGE (ru / en / he)", "ru");

	const tone = await askDefault("  FIRM_TONE (warm / formal / neutral)", "warm");

	// ────────────────────────────────────────────────────
	// Block 2 — Client Agent (WhatsApp)
	// ────────────────────────────────────────────────────

	section("Block 2 / 3 — Client Agent (WhatsApp)");
	note("WhatsApp = intake channel. Handles user messages, runs client pipeline.");

	const waEnabled = await askBool("  Enable WhatsApp client agent?", true);

	let waAuthDir = "";
	let waAllowedUserIds = "";

	if (waEnabled) {
		if (activePacks.length === 0 && !defaultPackId) {
			console.warn(
				"  ⚠️  Warning: WhatsApp client enabled but no packs configured.\n" +
					"     Clients won't be able to start a session without at least one pack.",
			);
		}

		waAuthDir = await askDefault("  WHATSAPP_AUTH_DIR (Baileys session storage)", `./.linda/auth/${firmId}-whatsapp`);

		note("Phone number whitelist (comma-separated, without @s.whatsapp.net).");
		note("Leave empty to allow all numbers.");
		waAllowedUserIds = await ask("  WHATSAPP_ALLOWED_USER_IDS: ");
	}

	// ────────────────────────────────────────────────────
	// Block 3 — Admin Agent (Telegram)
	// ────────────────────────────────────────────────────

	section("Block 3 / 3 — Admin Agent (Telegram)");
	note("Telegram = operator channel. Session browsing, overrides, client messaging.");
	note("Different tool surface and relaxed guardrails from client pipeline.");

	const tgEnabled = await askBool("  Enable Telegram admin agent?", true);

	let tgToken = "";
	let tgAllowedUserIds = "";

	if (tgEnabled) {
		tgToken = await ask("  TELEGRAM_BOT_TOKEN (from @BotFather): ");
		if (!tgToken) {
			console.error("  ✗ TELEGRAM_BOT_TOKEN is required when Telegram admin is enabled.");
			process.exit(1);
		}

		note("Telegram user IDs (numeric) — strongly recommended for production.");
		note("Leave empty to allow all (development only).");
		tgAllowedUserIds = await ask("  TELEGRAM_ALLOWED_USER_IDS (e.g. 123456789,987654321): ");

		if (!tgAllowedUserIds.trim()) {
			console.warn("  ⚠️  No allowed user IDs set — anyone who finds the bot can act as admin.");
		}
	}

	// ────────────────────────────────────────────────────
	// PSF + LLM (always required)
	// ────────────────────────────────────────────────────

	section("Infrastructure (PSF + LLM)");

	const psfBaseUrl = await askDefault("  PSF_BASE_URL", "http://localhost:3000");
	const psfSecret = await ask("  PSF_SHARED_SECRET: ");
	if (!psfSecret) {
		console.error("  ✗ PSF_SHARED_SECRET is required.");
		process.exit(1);
	}

	const anthropicKey = await ask("  ANTHROPIC_API_KEY (or leave empty if using another provider): ");

	// ────────────────────────────────────────────────────
	// Collect all answers, then generate
	// ────────────────────────────────────────────────────

	rl?.close();

	generateEnvFile({
		firmId,
		firmName,
		activePacks,
		defaultPackId,
		language,
		tone,
		waEnabled,
		waAuthDir,
		waAllowedUserIds,
		tgEnabled,
		tgToken,
		tgAllowedUserIds,
		psfBaseUrl,
		psfSecret,
		anthropicKey,
	});
}

wizard().catch((err) => {
	console.error("\n[create-firm] Error:", err.message);
	process.exit(1);
});
